### ISSUE TITLE
Using objects instead of IDs

### ISSUE THREAD

**Issue by ArchWand** [ArchWand/1984Bot#8]
At the start there's some channel ID's defined. Why don't we just define some channel objects (and a role object)? Would this not work since it's outside of an async function?

**Comment by dinolord919** [comment]
You would think it would work, especially if the objects were awaited before anything else ran. Unfortunately, when I tried this earlier, it simply refused to even acknowledge the presence of the channel object inside any of the functions. Outside the functions, it worked just fine. It's possible I was doing something wrong, since I tried this early on in development, so I think I'll leave this issue open and test it again.

**Comment by ArchWand** [comment]
I have done it.
